hw-01 Trie. Doronin Oleg
dorooleg/dotNet pull request #1
Opened 2017-09-13 08:33 UTC by dorooleg

2017-10-04 06:13 UTC, VMAtm requested changes
На данный момент оценка 7/10

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/Test/Properties/AssemblyInfo.cs
> +using System.Runtime.InteropServices;
Здесь и далее: Несмотря на то, что это системный файл, созданный не вами, было бы неплохо проверять и его на соответствие стилям - данный импорт в вашем файле не используется

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/Test/Properties/AssemblyInfo.cs
> +using System.Reflection;
Комментарий к файлу выше, так как он бинарный (хотя и текстовый внутри), и его не прокомментировать:
Смысл предупреждений о нарушении оформления (а там именно они) в том, чтобы их исправлять, а не ставить в игнор.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/Test/Settings.StyleCop
> +  <Analyzers>
Вопрос о выключении правил оформления кода остаётся открытым - такое количество выключенных правил вызывает большое вопросов.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/Test/StyleCop.Cache
> +<stylecopresultscache>
Подобный файл не несёт смысловой нагрузки и не должен быть в системе контроля версий кода.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Program.cs
> +﻿namespace TrieDataSctructure
Этот файл нужен только для того, чтобы ваш проект был собран как консольное приложение. Возможно, более логичным было бы сделать проект библиотекой, которой уже можно пользоваться  из других проектов (например, тестового).

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +            {
Даннон свойство и поле выше можно привести к виду:
            public IDictionary<char, Node> Childs { get; } = new Dictionary<char, Node>();

Так же сработает инициализация свойства только для чтения в конструкторе.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +        {
Идея реализации бора через поиск ребра, а не вершины, интересная, но мне потребовалось достаточно много времени понять ваше именование переменных. По факту, у вас `previousNode` - это текущая вершина (последняя при поиске слова в бору), то есть `currentNode`, а `currentNode` - это следующая вершина, при поиске слова она пуста, то есть это `nextNode`. С такой схемой именования, как мне кажется, понять ваш код будет гораздо проще.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +    using System.Collections.Generic;
Здесь и далее: Директивы `using` обычно записываются вне пространств имён

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +    public class Trie
в задании не было прямо сказано, но подразумевалось использование интерфейса для определения методов, которые нужно реализовать. Это простой способ отдать компилятору на проверку, вся ли требуемая функциональность реализована. Так же в этом случае в Unit-тестах можно определять тестируемый класс как ITrie, убирая привязку к конкретной реализации, и покрывая тестами только нужные методы.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +        private Node root;
внутренние (`private`) поля классов в .Net принято именовать, начиная с символа _. Поле `root` можно объявить `readonly`, так как оно инициализируется только в конструкторе.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +            Node previousNode = root;
Здесь и далее: Почему в одном случае вы используете полное имя класса, а в другом - ключевое слово `var`,

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +                currentNode.CountPrefixes++;
Здесь и далее: так как текущее значение переменной никому не требуется, можно писать так: `++currentNode.CountPrefixes;` (этот момент упомянут в лекциях в разделе про цикл for).

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +            public bool Terminal { get; set; }
Поля типа `bool` удобнее называть с префиксом `Is`, так понятнее, что это поле означает, и то, что оно типа `bool`

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +        public bool Contains(string element)
Метод `Contains` реализован неверно, минимальный тест, на котором сломается:

        Assert.IsTrue(trie.Add("common1"));
        // выбросит ошибку из-за того, что метод Contains посчитает, что слово уже добавлено
        Assert.IsTrue(trie.Add("common2"));

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +                if (currentNode == null)
Согласно отчёту dotCover, данный блок `if` не покрыт тестами.

2017-10-04 06:13 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +            => (GetLastEdge(prefix).currentNode?.CountPrefixes).GetValueOrDefault(0);
Подобная длинная цепочка вызовов вызывает вопросы. Несмотря на то, что метод всё ещё работает за константное время, он тратит некоторое время на то, чтобы вернуть и так сущуствующую ссылку на `root`. Почему нельзя было просто написать `return root.CountPrefixes`?

2017-10-05 13:38 UTC, dorooleg commented on trie/trie/Test/Settings.StyleCop
> +  <Analyzers>
Я отключил warning о том что обращение к внутренним полям класса должно происходить через this. И также warning связанные с комментированием кода.

2017-10-05 13:38 UTC, dorooleg commented on trie/trie/trie/Trie.cs
> +    using System.Collections.Generic;
StyleCop говорит что нужно писать внутри namespace.

2017-10-05 13:40 UTC, dorooleg commented on trie/trie/trie/Trie.cs
> +        private Node root;
StyleCop:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		SA1309 : CSharp.Naming : Field names must not start with an underscore.	trie	C:\Users\Oleg\Desktop\dotNet\trie\trie\trie\Trie.cs	7	

Исправил на _ т.к. мне самому приятнее сразу отличать переменные принадлежащие классу

2017-10-05 13:42 UTC, dorooleg commented on trie/trie/trie/Trie.cs
> +            Node previousNode = root;
Если тип можно увидеть на одном экране. Например передается string и я делаю foreach (var .., то и так понятно какой тип у .. . Но наверное нужно полностью избавиться от var. Поэтому так и сделал

2017-10-05 13:43 UTC, dorooleg commented on trie/trie/trie/Trie.cs
> +                currentNode.CountPrefixes++;
Не совсем понимаю чем это лучше currentNode.CountPrefixes++ ?

2017-10-05 13:46 UTC, dorooleg commented
Все остальные изменения сделал

2017-10-13 04:48 UTC, VMAtm approved these changes
Оценка обновлена до 9/10

2017-10-13 04:48 UTC, VMAtm commented on trie/trie/trie/trie.csproj
> +    <Reference Include="System.Data.DataSetExtensions" />
Здесь и далее: некоторые ссылки из шаблона не используются и могут быть спокойно удалены

2017-10-13 04:48 UTC, VMAtm commented on trie/trie/trie/Trie.cs
> +            previousNode.CountPrefixes--;
так как текущее значение переменной никому не требуется, можно писать так: `--previousNode.CountPrefixes;` (этот момент упомянут в лекциях в разделе про цикл `for`).

2017-10-13 04:48 UTC, VMAtm commented on trie/trie/trie/ITrie.cs
> +        /// Expected complexity: O(|element|)
На будущее: тройной комментарий в C# - это XML-документация, чего здесь не выполнено. Для простого комментирования используйте `//`

2017-10-26 10:55 UTC, merged